name: obsidian-publish-quartz

services:
  quartz:
    build:
      context: ${CODE_DIR:-.}
      dockerfile: Dockerfile
      args:
        VAULT_DIR: ${VAULT_DIR:-./content}
    image: ${IMAGE_TAG:-quartz:latest}
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    # Config your own network
    networks:
      - nas
    ports:
      - ${PORT}:8080

networks:
  nas:
    external: true
